In [1]:
import pandas as pd

![](https://s3-sa-east-1.amazonaws.com/lcpi/2d4e73ef-5f98-4fa4-95c0-77f9115db1ad.png)

### ETL
 - Extract
 - Transform
 - Load

#### Lendo dados da memória

Fonte: https://pt.wikipedia.org/wiki/Lista_de_municípios_do_Ceará_por_população

In [6]:
df = pd.read_clipboard()
df

Empty DataFrame
Columns: [https://gist.github.com/denandreychuk/b9aa812f10e4b60368cff69c6384a210#file-100-sales-records-csv]
Index: []

In [7]:
df.to_csv('teste.csv')

### Lendo dados da web

In [9]:
#Fonte: 'https://pbpython.com/pandas-html-table.html'

#### Lendo dados de uma API

In [3]:
#endpoint = https://integrasus.saude.ce.gov.br/#/indicadores/indicadores-hospitalares/loc-estab-saude-ceara
import pandas as pd
df = pd.read_json('https://integrasus.saude.ce.gov.br/api/coronavirus/curva-epidemiologica?dataInicio=2020-01-01&dataFim=2023-03-05&minDate=2020-01-01&maxDate=2023-03-05&tipo=Confirmados&idMunicipio=&idRegiaoSaude=&idMacrorregiao=&casosHospitalizados=false&casosProfissionais=false&casosIndigenas=false&casosEstudante=false')
df

      quantidade  qtdObito  quantidadeSuspeitos  mediaMovel        data
0            257         4                    8        0.00  15/03/2020
1            193         8                   10        0.00  16/03/2020
2            215         5                    2        0.00  17/03/2020
3            267        12                    5        0.00  18/03/2020
4            234        11                    7        0.00  19/03/2020
...          ...       ...                  ...         ...         ...
1081          75         0                    1       65.00  01/03/2023
1082          62         0                    0       64.14  02/03/2023
1083          83         0                    1       63.42  03/03/2023
1084          66         0                    1       64.85  04/03/2023
1085          70         1                    1       63.00  05/03/2023

[1086 rows x 5 columns]

#### Leitura de dados CSV

In [6]:
#'https://raw.githubusercontent.com/cyb3rl3x/datasets/refs/heads/main/btc_2025.csv'

#### Lendo dados de uma API via package

In [ ]:
#!pip install yfinance

In [8]:
import yfinance as yf

df = yf.download('BTC-USD', start='2025-01-01', interval='1d', multi_level_index=False)

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

#### Libs para construção de crawlers e scrappers

- requests
- beautifulsoup
- mechanicalsoup
- selenium

In [ ]:
import requests as req

res = req.get('https://g1.globo.com')

res.text

In [ ]:
import requests

new_data = {
    "userID": 1,
    "id": 1,
    "title": "Fazendo um POST request",
    "body": "Este dado foi criado."
}

url_post = "https://jsonplaceholder.typicode.com/posts"

In [ ]:
res.json()